import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ClerkLoaded, ClerkProvider } from "@clerk/nextjs";
import { NavbarRoutes } from "@/components/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>


      <html lang="en">
        <body>
          <Toaster />
          <NavbarRoutes />
          <ClerkLoaded>
            <main className="min-h-screen">
              {children}
            </main>
          </ClerkLoaded>
        </body>
      </html>


    </ClerkProvider >
  )
}
